### ISSUE TITLE
Exposure of CPU/GPU usage

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-capabilities#171]
Breaking this item out from #170.  (@NalaGinrut, for tracking)

1. About the CPU/GPU usage query

> Real time feedback about the playback so an adaptative streaming can alter the quality of the content based on actual user perceived quality. Such information will allow websites to react to a pick of CPU/GPU usage in real time.

`Question:` Does this mean there's an API will expose the usage of CPU/GPU without users' explicit permission?

**Comment by chcunningham** [comment]
>  Does this mean there's an API will expose the usage of CPU/GPU without users' explicit permission?

No. 

This section of the spec is trying to convey that MediaCapabilities could be used in combination with the (distinct) [Media Playback Quality API](https://w3c.github.io/media-playback-quality/). MediaCapabilities gives before-playback info about support and performance, while Media Playback Quality gives real-time feedback on how a video is performing. The combination is useful because the before-playback performance predictions may turn out to be wrong, particularly if the user starts a GPU / CPU intensive task (say playing a game with demanding graphics) while they watch their video. The MediaPlaybackQuality API does not actually give CPU/GPU usage numbers. Instead it will tell you if your video is "dropping frames", which occurs because the decoder can not keep up with the framerate.

**Comment by NalaGinrut** [comment]
@chcunningham Thanks, this one is clear and done.
cc @samuelweiler

**Comment by chcunningham** [comment]
Thanks. Please re-open if needed.
