### ISSUE TITLE
Intentional manipulation of battery status

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-capabilities#173]
Breaking this item out from #170.  (@NalaGinrut, for tracking)

2. About the `powerEfficient` field of `MediaCapabilitiesInfo`

> A MediaCapabilitiesInfo has associated supported, smooth, powerEfficient fields which are booleans.
Authors can use powerEfficient in concordance with the Battery Status API [battery-status] in order to determine whether the media they would like to play is appropriate for the user configuration. It is worth noting that even when a device is not power constrained, high power usage has side effects such as increasing the temperature or the fans noise. 

...

`Question 2:` Is it possible to increase the temperature intendedly with `powerEfficient` field?

**Comment by chcunningham** [comment]
> Is it possible to increase the temperature intendedly with powerEfficient field?

If used the powerEfficient field to determine which configurations were _not_ power efficient, you could theoretically then play back videos meeting those criteria and potentially increase the machine temperature. 

But, this is definitely not the most effective way to increase the machine temperature. For instance, you could do things like mine bitcoin or other computation intensive tasks that are not related to this API.

**Comment by samuelweiler** [comment]
@NalaGinrut, does this answer satisfy you?

Downgrading this to -tracker, pending any further discussion.

**Comment by NalaGinrut** [comment]
@chcunningham I still have concerns about this field.

I may want to keep my machine performance in a fair low efficiency. For example, I want to save the power of my laptop, or I'm an environmentalist so that I prefer to keep my device in a less carbon fingerprint, if the playback is good enough for me, I may not think a higher performance playback is better for me. When the power management of the OS was set to a demand policy, it may increase the power usage if the application requires it. 

I'm a bit concern if the user has to negatively accept this field to increase the power usage just because the application developers thought it's good. Is there any way to ignore this field or opt-out if users don't want it? 

cc @pes10k @samuelweiler

**Comment by NalaGinrut** [comment]
This may sound not a privacy issue. But I think privacy is not only about what could be leaked, but also about that people can refuse to accept what they don't want.

**Comment by chcunningham** [comment]
> I'm a bit concern if the user has to passively accept this field to increase the power usage just because the application developers thought it's good.

Ah, I think I understand the concern. Let me give a little more background. For this API 'powerEfficient' is not like the 'eco' mode of modern cars, where you are giving up performance to expend less energy. Instead, powerEfficient generally reflects that the machine has specialized gpu/cpu support for accelerating encoding or decoding a particular type of video. This means that, unlike the car example, for video powerEfficiency and performance are generally aligned. Sites will not choose to avoid powerEfficient=true out of concern for decreased performance.

**Comment by chcunningham** [comment]
> Instead, powerEfficient generally reflects that the machine has specialized gpu/cpu support for accelerating encoding or decoding a particular type of video. 

Two things expand on this:
- such GPU/CPU support is very common. This alone will not be uniquely identifying
- we may also return powerEfficient = true in some cases where GPU/CPU support is not available, but the configuration is known to still draw a very small amount of power (e.g. lower resolutions of video)

**Comment by NalaGinrut** [comment]
> Sites will not choose to avoid powerEfficient=true out of concern for decreased performance.

I understand the site developer will be inclined to set it to `true`. But is there a way for users to reject/ingore it if they want.

> we may also return powerEfficient = true in some cases where GPU/CPU support is not available

I think you've explained this point in another issue, althought I'm still confused about the formal expected activity of `powerEfficient` since it seems unnecessary to be real efficient even it's set to `true`.

Anyway, now that it's an option rather than a forced activity to configure `powerEfficient`, I think users may have right to reject/ignore it. However, the current situation implies that only the site developer can decide whether to enable it.

**Comment by chcunningham** [comment]
> I understand the site developer will be inclined to set it to true. But is there a way for users to reject/ignore it if they want?

A site would not "set it to true". This boolean is set by the user agent. A site may read it and prefer configurations where the value was `true`.

User agents could implement MediaCapabilities (and `<video>` generally) in a way that only supports codecs that are (or are not) power efficient. I'm not sure if this is what you have in mind? I wouldn't recommend doing this, as it will constrain what types of videos a site may send you (generally reducing the sites ability to optimize for whatever experience metrics they prioritize).

**Comment by NalaGinrut** [comment]
OK, I see, this option is not forced from the perspective of the standard. The site maker may provide an option for users if they really care (although we may think no one care). So it's not the issue of the spec or browser developers.
This one is clear and done, thanks!
@pes10k
