### ISSUE TITLE
Deprecate isTypeSupported and canPlayType

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/media-capabilities#3]
In favour of the decoding capabilities api from this specification.

**Comment by foolip** [comment]
Does the API make promises for only HTMLMediaElement and MediaSource, or does it also cover Web Audio's [decodeAudioData](https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-decodeAudioData-Promise-AudioBuffer--ArrayBuffer-audioData-DecodeSuccessCallback-successCallback-DecodeErrorCallback-errorCallback)?

I wonder if instead of a new entry-point (`navigator.mediaCapabilities`), this spec could define a mixin with a static `query` method that is added to HTMLMediaElement and MediaSource individually, in closer proximity to the original methods.

**Comment by mounirlamouri** [comment]
We are considering having something like this for EME (I need to write something about this). Did you imagine a `static` method on `HTMLMediaElement` and `MediaSource`? I guess we could handle Web Audio by adding a new type.

**Comment by foolip** [comment]
Yes, I was thinking some method with a name other than `isTypeSupported` and `canPlayType` that you add to whatever contexts you want to ask these questions, to replace the `MediaConfigurationType` enum. If that makes sense?

**Comment by marcoscaceres** [comment]
https://github.com/whatwg/html/issues/10460

**Comment by marcoscaceres** [comment]
filed https://github.com/w3c/media-source/issues/355

**Comment by marcoscaceres** [comment]
We should reopen this if our spec falls short.
